// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { createContextReferenceApiV1ConciergeContextReferencesPostData, createContextReferenceApiV1ConciergeContextReferencesPostErrors, createContextReferenceApiV1ConciergeContextReferencesPostResponses, getBoxArtApiV1CatalogGamesGameIdBoxArtGetData, getBoxArtApiV1CatalogGamesGameIdBoxArtGetErrors, getBoxArtApiV1CatalogGamesGameIdBoxArtGetResponses, getGameApiV1CatalogGamesGameIdGetData, getGameApiV1CatalogGamesGameIdGetErrors, getGameApiV1CatalogGamesGameIdGetResponses, healthApiV1HealthGetData, healthApiV1HealthGetErrors, healthApiV1HealthGetResponses, listFacetsApiV1CatalogFacetsGetData, listFacetsApiV1CatalogFacetsGetErrors, listFacetsApiV1CatalogFacetsGetResponses, listGamesApiV1CatalogGamesGetData, listGamesApiV1CatalogGamesGetErrors, listGamesApiV1CatalogGamesGetResponses, telegramWebhookApiV1ConciergeTelegramWebhookPostData, telegramWebhookApiV1ConciergeTelegramWebhookPostErrors, telegramWebhookApiV1ConciergeTelegramWebhookPostResponses, validateContextReferenceApiV1ConciergeContextReferencesValidatePostData, validateContextReferenceApiV1ConciergeContextReferencesValidatePostErrors, validateContextReferenceApiV1ConciergeContextReferencesValidatePostResponses, versionApiV1SystemVersionGetData, versionApiV1SystemVersionGetErrors, versionApiV1SystemVersionGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class CatalogService {
    /**
     * List Facets
     */
    public static listFacetsApiV1CatalogFacetsGet<ThrowOnError extends boolean = true>(options?: Options<listFacetsApiV1CatalogFacetsGetData, ThrowOnError>) {
        return (options?.client ?? client).get<listFacetsApiV1CatalogFacetsGetResponses, listFacetsApiV1CatalogFacetsGetErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/catalog/facets',
            ...options
        });
    }
    
    /**
     * List Games
     */
    public static listGamesApiV1CatalogGamesGet<ThrowOnError extends boolean = true>(options?: Options<listGamesApiV1CatalogGamesGetData, ThrowOnError>) {
        return (options?.client ?? client).get<listGamesApiV1CatalogGamesGetResponses, listGamesApiV1CatalogGamesGetErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/catalog/games',
            ...options
        });
    }
    
    /**
     * Get Game
     */
    public static getGameApiV1CatalogGamesGameIdGet<ThrowOnError extends boolean = true>(options: Options<getGameApiV1CatalogGamesGameIdGetData, ThrowOnError>) {
        return (options.client ?? client).get<getGameApiV1CatalogGamesGameIdGetResponses, getGameApiV1CatalogGamesGameIdGetErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/catalog/games/{game_id}',
            ...options
        });
    }
    
    /**
     * Get Box Art
     */
    public static getBoxArtApiV1CatalogGamesGameIdBoxArtGet<ThrowOnError extends boolean = true>(options: Options<getBoxArtApiV1CatalogGamesGameIdBoxArtGetData, ThrowOnError>) {
        return (options.client ?? client).get<getBoxArtApiV1CatalogGamesGameIdBoxArtGetResponses, getBoxArtApiV1CatalogGamesGameIdBoxArtGetErrors, ThrowOnError>({
            responseType: 'blob',
            url: '/api/v1/catalog/games/{game_id}/box-art',
            ...options
        });
    }
}

export class ConciergeService {
    /**
     * Create Context Reference
     */
    public static createContextReferenceApiV1ConciergeContextReferencesPost<ThrowOnError extends boolean = true>(options: Options<createContextReferenceApiV1ConciergeContextReferencesPostData, ThrowOnError>) {
        return (options.client ?? client).post<createContextReferenceApiV1ConciergeContextReferencesPostResponses, createContextReferenceApiV1ConciergeContextReferencesPostErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/concierge/context-references',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Validate Context Reference
     */
    public static validateContextReferenceApiV1ConciergeContextReferencesValidatePost<ThrowOnError extends boolean = true>(options: Options<validateContextReferenceApiV1ConciergeContextReferencesValidatePostData, ThrowOnError>) {
        return (options.client ?? client).post<validateContextReferenceApiV1ConciergeContextReferencesValidatePostResponses, validateContextReferenceApiV1ConciergeContextReferencesValidatePostErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/concierge/context-references/validate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Telegram Webhook
     */
    public static telegramWebhookApiV1ConciergeTelegramWebhookPost<ThrowOnError extends boolean = true>(options?: Options<telegramWebhookApiV1ConciergeTelegramWebhookPostData, ThrowOnError>) {
        return (options?.client ?? client).post<telegramWebhookApiV1ConciergeTelegramWebhookPostResponses, telegramWebhookApiV1ConciergeTelegramWebhookPostErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/concierge/telegram/webhook',
            ...options
        });
    }
}

export class SystemService {
    /**
     * Health
     */
    public static healthApiV1HealthGet<ThrowOnError extends boolean = true>(options?: Options<healthApiV1HealthGetData, ThrowOnError>) {
        return (options?.client ?? client).get<healthApiV1HealthGetResponses, healthApiV1HealthGetErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/health',
            ...options
        });
    }
    
    /**
     * Version
     */
    public static versionApiV1SystemVersionGet<ThrowOnError extends boolean = true>(options?: Options<versionApiV1SystemVersionGetData, ThrowOnError>) {
        return (options?.client ?? client).get<versionApiV1SystemVersionGetResponses, versionApiV1SystemVersionGetErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/system/version',
            ...options
        });
    }
}
