// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * VersionResponse
 */
export type VersionResponse = {
    /**
     * App Version
     */
    app_version: string;
    /**
     * Correlation Id
     */
    correlation_id: string;
};

export type healthApiV1HealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type healthApiV1HealthGetResponses = {
    /**
     * Response Health Api V1 Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type healthApiV1HealthGetResponse = healthApiV1HealthGetResponses[keyof healthApiV1HealthGetResponses];

export type versionApiV1SystemVersionGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/version';
};

export type versionApiV1SystemVersionGetResponses = {
    /**
     * Successful Response
     */
    200: VersionResponse;
};

export type versionApiV1SystemVersionGetResponse = versionApiV1SystemVersionGetResponses[keyof versionApiV1SystemVersionGetResponses];
