// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AttributeOrigin
 */
export type AttributeOrigin = {
    /**
     * Captured At
     */
    captured_at?: string | null;
    /**
     * Source
     */
    source: string;
    /**
     * Source Record Id
     */
    source_record_id: string;
    /**
     * Source Version
     */
    source_version: string;
};

/**
 * GameAttributes
 */
export type GameAttributes = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Developer
     */
    developer?: string | null;
    /**
     * Edition
     */
    edition?: string | null;
    /**
     * Genre
     */
    genre?: string | null;
    /**
     * Included Items
     */
    included_items?: Array<string> | null;
    /**
     * Platform
     */
    platform?: string | null;
    /**
     * Publisher
     */
    publisher?: string | null;
    /**
     * Rating
     */
    rating?: string | null;
    /**
     * Region
     */
    region?: string | null;
    /**
     * Release Date
     */
    release_date?: string | null;
    /**
     * Release Date Granularity
     */
    release_date_granularity?: 'year' | 'month' | 'day' | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Year
     */
    year?: string | null;
};

/**
 * GameFacetsResponse
 */
export type GameFacetsResponse = {
    /**
     * Genres
     */
    genres: Array<string>;
    /**
     * Platforms
     */
    platforms: Array<string>;
};

/**
 * GameListResponse
 */
export type GameListResponse = {
    /**
     * Commerce Status
     */
    commerce_status: 'available' | 'unavailable';
    /**
     * Items
     */
    items: Array<GameResponse>;
    /**
     * Next Cursor
     */
    next_cursor: string | null;
};

/**
 * GameResponse
 */
export type GameResponse = {
    attributes: GameAttributes;
    /**
     * Cover Attribution
     */
    cover_attribution: string;
    /**
     * Cover Url
     */
    cover_url: string;
    /**
     * Id
     */
    id: string;
    /**
     * Offers
     */
    offers?: Array<OfferResponse> | null;
    /**
     * Origin By Attribute
     */
    origin_by_attribute: {
        [key: string]: AttributeOrigin;
    };
    /**
     * Platform
     */
    platform: string;
    /**
     * Source
     */
    source: string;
    /**
     * Source Record Id
     */
    source_record_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Verified At
     */
    verified_at: string;
    /**
     * Version
     */
    version: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * OfferResponse
 */
export type OfferResponse = {
    /**
     * Available Units
     */
    available_units: number;
    /**
     * Condition Summary
     */
    condition_summary: string;
    /**
     * Currency
     */
    currency: 'BRL';
    /**
     * Demo Rank
     */
    demo_rank: number;
    /**
     * Id
     */
    id: string;
    /**
     * Mode
     */
    mode: 'purchase' | 'rental';
    /**
     * Price Minor
     */
    price_minor: number;
    /**
     * Sandbox
     */
    sandbox: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VersionResponse
 */
export type VersionResponse = {
    /**
     * App Version
     */
    app_version: string;
    /**
     * Correlation Id
     */
    correlation_id: string;
};

export type listFacetsApiV1CatalogFacetsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/catalog/facets';
};

export type listFacetsApiV1CatalogFacetsGetResponses = {
    /**
     * Successful Response
     */
    200: GameFacetsResponse;
};

export type listFacetsApiV1CatalogFacetsGetResponse = listFacetsApiV1CatalogFacetsGetResponses[keyof listFacetsApiV1CatalogFacetsGetResponses];

export type listGamesApiV1CatalogGamesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Q
         */
        q?: string | null;
        /**
         * Platform
         */
        platform?: string | null;
        /**
         * Genre
         */
        genre?: string | null;
        /**
         * Availability
         */
        availability?: 'available' | 'unavailable' | null;
        /**
         * Sort
         */
        sort?: 'catalog' | 'demo_popular';
    };
    url: '/api/v1/catalog/games';
};

export type listGamesApiV1CatalogGamesGetErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
    /**
     * Commerce indisponível.
     */
    503: unknown;
};

export type listGamesApiV1CatalogGamesGetError = listGamesApiV1CatalogGamesGetErrors[keyof listGamesApiV1CatalogGamesGetErrors];

export type listGamesApiV1CatalogGamesGetResponses = {
    /**
     * Successful Response
     */
    200: GameListResponse;
};

export type listGamesApiV1CatalogGamesGetResponse = listGamesApiV1CatalogGamesGetResponses[keyof listGamesApiV1CatalogGamesGetResponses];

export type getGameApiV1CatalogGamesGameIdGetData = {
    body?: never;
    headers?: {
        /**
         * If-None-Match
         */
        'If-None-Match'?: string | null;
    };
    path: {
        /**
         * Game Id
         */
        game_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/games/{game_id}';
};

export type getGameApiV1CatalogGamesGameIdGetErrors = {
    /**
     * Published game not found.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type getGameApiV1CatalogGamesGameIdGetError = getGameApiV1CatalogGamesGameIdGetErrors[keyof getGameApiV1CatalogGamesGameIdGetErrors];

export type getGameApiV1CatalogGamesGameIdGetResponses = {
    /**
     * Successful Response
     */
    200: GameResponse;
    /**
     * The published game has not changed.
     */
    304: undefined;
};

export type getGameApiV1CatalogGamesGameIdGetResponse = getGameApiV1CatalogGamesGameIdGetResponses[keyof getGameApiV1CatalogGamesGameIdGetResponses];

export type getBoxArtApiV1CatalogGamesGameIdBoxArtGetData = {
    body?: never;
    headers?: {
        /**
         * If-None-Match
         */
        'If-None-Match'?: string | null;
    };
    path: {
        /**
         * Game Id
         */
        game_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/games/{game_id}/box-art';
};

export type getBoxArtApiV1CatalogGamesGameIdBoxArtGetErrors = {
    /**
     * Published box art not found.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type getBoxArtApiV1CatalogGamesGameIdBoxArtGetError = getBoxArtApiV1CatalogGamesGameIdBoxArtGetErrors[keyof getBoxArtApiV1CatalogGamesGameIdBoxArtGetErrors];

export type getBoxArtApiV1CatalogGamesGameIdBoxArtGetResponses = {
    /**
     * Authorized published cover image.
     */
    200: Blob | File;
    /**
     * The published cover has not changed.
     */
    304: undefined;
};

export type getBoxArtApiV1CatalogGamesGameIdBoxArtGetResponse = getBoxArtApiV1CatalogGamesGameIdBoxArtGetResponses[keyof getBoxArtApiV1CatalogGamesGameIdBoxArtGetResponses];

export type healthApiV1HealthGetData = {
    body?: never;
    headers?: {
        /**
         * UUID de correlação opcional. Um UUID é gerado quando ele não é informado ou é inválido.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type healthApiV1HealthGetErrors = {
    /**
     * Problem
     *
     * Resposta de problema padronizada.
     */
    500: {
        /**
         * Code
         */
        code: string;
        /**
         * Correlation Id
         */
        correlation_id: string;
        /**
         * Status
         */
        status: number;
        /**
         * Title
         */
        title: string;
        /**
         * Type
         */
        type?: string;
    };
};

export type healthApiV1HealthGetError = healthApiV1HealthGetErrors[keyof healthApiV1HealthGetErrors];

export type healthApiV1HealthGetResponses = {
    /**
     * Response Health Api V1 Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type healthApiV1HealthGetResponse = healthApiV1HealthGetResponses[keyof healthApiV1HealthGetResponses];

export type versionApiV1SystemVersionGetData = {
    body?: never;
    headers?: {
        /**
         * UUID de correlação opcional. Um UUID é gerado quando ele não é informado ou é inválido.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/system/version';
};

export type versionApiV1SystemVersionGetErrors = {
    /**
     * Problem
     *
     * Resposta de problema padronizada.
     */
    500: {
        /**
         * Code
         */
        code: string;
        /**
         * Correlation Id
         */
        correlation_id: string;
        /**
         * Status
         */
        status: number;
        /**
         * Title
         */
        title: string;
        /**
         * Type
         */
        type?: string;
    };
};

export type versionApiV1SystemVersionGetError = versionApiV1SystemVersionGetErrors[keyof versionApiV1SystemVersionGetErrors];

export type versionApiV1SystemVersionGetResponses = {
    /**
     * Successful Response
     */
    200: VersionResponse;
};

export type versionApiV1SystemVersionGetResponse = versionApiV1SystemVersionGetResponses[keyof versionApiV1SystemVersionGetResponses];
