// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * GameListResponse
 */
export type GameListResponse = {
    /**
     * Items
     */
    items: Array<GameResponse>;
    /**
     * Next Cursor
     */
    next_cursor: string | null;
};

/**
 * GameResponse
 */
export type GameResponse = {
    /**
     * Attributes
     */
    attributes: {
        [key: string]: unknown;
    };
    /**
     * Cover Attribution
     */
    cover_attribution: string;
    /**
     * Cover Url
     */
    cover_url: string;
    /**
     * Id
     */
    id: string;
    /**
     * Origin By Attribute
     */
    origin_by_attribute: {
        [key: string]: unknown;
    };
    /**
     * Platform
     */
    platform: string;
    /**
     * Source
     */
    source: string;
    /**
     * Source Record Id
     */
    source_record_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Verified At
     */
    verified_at: string;
    /**
     * Version
     */
    version: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VersionResponse
 */
export type VersionResponse = {
    /**
     * App Version
     */
    app_version: string;
    /**
     * Correlation Id
     */
    correlation_id: string;
};

export type listGamesApiV1CatalogGamesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Platform
         */
        platform?: string | null;
    };
    url: '/api/v1/catalog/games';
};

export type listGamesApiV1CatalogGamesGetErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type listGamesApiV1CatalogGamesGetError = listGamesApiV1CatalogGamesGetErrors[keyof listGamesApiV1CatalogGamesGetErrors];

export type listGamesApiV1CatalogGamesGetResponses = {
    /**
     * Successful Response
     */
    200: GameListResponse;
};

export type listGamesApiV1CatalogGamesGetResponse = listGamesApiV1CatalogGamesGetResponses[keyof listGamesApiV1CatalogGamesGetResponses];

export type getGameApiV1CatalogGamesGameIdGetData = {
    body?: never;
    headers?: {
        /**
         * If-None-Match
         */
        'If-None-Match'?: string | null;
    };
    path: {
        /**
         * Game Id
         */
        game_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/games/{game_id}';
};

export type getGameApiV1CatalogGamesGameIdGetErrors = {
    /**
     * Published game not found.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type getGameApiV1CatalogGamesGameIdGetError = getGameApiV1CatalogGamesGameIdGetErrors[keyof getGameApiV1CatalogGamesGameIdGetErrors];

export type getGameApiV1CatalogGamesGameIdGetResponses = {
    /**
     * Successful Response
     */
    200: GameResponse;
};

export type getGameApiV1CatalogGamesGameIdGetResponse = getGameApiV1CatalogGamesGameIdGetResponses[keyof getGameApiV1CatalogGamesGameIdGetResponses];

export type getBoxArtApiV1CatalogGamesGameIdBoxArtGetData = {
    body?: never;
    path: {
        /**
         * Game Id
         */
        game_id: string;
    };
    query?: never;
    url: '/api/v1/catalog/games/{game_id}/box-art';
};

export type getBoxArtApiV1CatalogGamesGameIdBoxArtGetErrors = {
    /**
     * Published box art not found.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type getBoxArtApiV1CatalogGamesGameIdBoxArtGetError = getBoxArtApiV1CatalogGamesGameIdBoxArtGetErrors[keyof getBoxArtApiV1CatalogGamesGameIdBoxArtGetErrors];

export type getBoxArtApiV1CatalogGamesGameIdBoxArtGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type healthApiV1HealthGetData = {
    body?: never;
    headers?: {
        /**
         * UUID de correlação opcional. Um UUID é gerado quando ele não é informado ou é inválido.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type healthApiV1HealthGetErrors = {
    /**
     * Problem
     *
     * Resposta de problema padronizada.
     */
    500: {
        /**
         * Code
         */
        code: string;
        /**
         * Correlation Id
         */
        correlation_id: string;
        /**
         * Status
         */
        status: number;
        /**
         * Title
         */
        title: string;
        /**
         * Type
         */
        type?: string;
    };
};

export type healthApiV1HealthGetError = healthApiV1HealthGetErrors[keyof healthApiV1HealthGetErrors];

export type healthApiV1HealthGetResponses = {
    /**
     * Response Health Api V1 Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type healthApiV1HealthGetResponse = healthApiV1HealthGetResponses[keyof healthApiV1HealthGetResponses];

export type versionApiV1SystemVersionGetData = {
    body?: never;
    headers?: {
        /**
         * UUID de correlação opcional. Um UUID é gerado quando ele não é informado ou é inválido.
         */
        'X-Correlation-ID'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/system/version';
};

export type versionApiV1SystemVersionGetErrors = {
    /**
     * Problem
     *
     * Resposta de problema padronizada.
     */
    500: {
        /**
         * Code
         */
        code: string;
        /**
         * Correlation Id
         */
        correlation_id: string;
        /**
         * Status
         */
        status: number;
        /**
         * Title
         */
        title: string;
        /**
         * Type
         */
        type?: string;
    };
};

export type versionApiV1SystemVersionGetError = versionApiV1SystemVersionGetErrors[keyof versionApiV1SystemVersionGetErrors];

export type versionApiV1SystemVersionGetResponses = {
    /**
     * Successful Response
     */
    200: VersionResponse;
};

export type versionApiV1SystemVersionGetResponse = versionApiV1SystemVersionGetResponses[keyof versionApiV1SystemVersionGetResponses];
